eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.43.248:8761/eureka/
      
server:
  port: 8764
  
spring:
  application:
    name: eshop-inventory-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.43.179:3306/eshop?useSSL=true
    username: root
    password: root